import { useState } from 'react';
import { useNavigate } from 'react-router';
import { Badge } from '../components/Badge';
import { Button } from '../components/Button';
import { ChevronDown, ChevronRight, Download, ArrowLeft } from 'lucide-react';

export function ComplianceReport() {
  const navigate = useNavigate();
  const [expandedCategories, setExpandedCategories] = useState<Record<string, boolean>>({
    informed: true,
    eligibility: false,
    safety: false
  });
  const [showProtocol, setShowProtocol] = useState(true);

  const toggleCategory = (cat: string) => {
    setExpandedCategories(prev => ({ ...prev, [cat]: !prev[cat] }));
  };

  const complianceScore = 78;

  const categories = [
    {
      id: 'informed',
      title: 'Informed Consent Process',
      status: 'pass',
      items: [
        { requirement: 'Consent form includes all required elements', assessment: 'Compliant', reference: '21 CFR 50.25', section: '3.2' },
        { requirement: 'Process for obtaining consent documented', assessment: 'Compliant', reference: '21 CFR 50.27', section: '3.3' }
      ]
    },
    {
      id: 'eligibility',
      title: 'Eligibility Criteria',
      status: 'warning',
      items: [
        { requirement: 'Inclusion criteria clearly defined', assessment: 'Needs clarification', reference: 'ICH E6', section: '4.1' },
        { requirement: 'Exclusion criteria justified', assessment: 'Missing justification', reference: 'ICH E6', section: '4.2' }
      ]
    },
    {
      id: 'safety',
      title: 'Safety Monitoring',
      status: 'fail',
      items: [
        { requirement: 'Adverse event reporting plan', assessment: 'Not documented', reference: '21 CFR 312.32', section: '6.3' },
        { requirement: 'Data Safety Monitoring Board', assessment: 'Incomplete structure', reference: 'ICH E6', section: '6.4' }
      ]
    }
  ];

  const flaggedIssues = [
    { severity: 'critical', section: '6.3', issue: 'Adverse event reporting timeline not specified', reference: '21 CFR 312.32', status: 'unresolved' },
    { severity: 'major', section: '4.2', issue: 'Age exclusion criteria lacks scientific rationale', reference: 'ICH E6', status: 'in_progress' },
    { severity: 'minor', section: '7.1', issue: 'Statistical analysis plan missing interim analysis details', reference: 'ICH E9', status: 'resolved' }
  ];

  const historicalData = [
    { name: 'PROT-001', score: 85 },
    { name: 'PROT-002', score: 72 },
    { name: 'PROT-003', score: 91 },
    { name: 'PROT-004', score: 78 },
    { name: 'Current', score: complianceScore }
  ];

  return (
    <div className="flex gap-4">
      <div className="flex-[13] overflow-auto">
        <div className="flex items-center gap-4 mb-6">
          <button
            onClick={() => navigate(-1)}
            className="flex items-center gap-2 text-[#E8930A] hover:underline"
          >
            <ArrowLeft className="w-4 h-4" />
            Back
          </button>
          <h1 className="text-2xl text-[#6B0D0D]">Compliance Analysis Report</h1>
        </div>
        <div className="bg-white border border-[#E0E0E0] rounded p-6 mb-6">
          <div className="flex items-start justify-between mb-4">
            <div>
              <div className="text-sm text-[#6B6B6B] mb-1">PROT-2024-012</div>
              <div className="text-lg mb-1">Gene Therapy for Hemophilia</div>
              <Badge variant="phase">Phase II</Badge>
            </div>
            <div className="text-center">
              <div className={`text-6xl mb-2 ${complianceScore >= 80 ? 'text-[#6B0D0D]' : 'text-[#DC2626]'}`}>
                {complianceScore}%
              </div>
              <div className="relative w-32 h-32 mx-auto">
                <svg className="transform -rotate-90 w-32 h-32">
                  <circle
                    cx="64"
                    cy="64"
                    r="56"
                    stroke="#E0E0E0"
                    strokeWidth="8"
                    fill="none"
                  />
                  <circle
                    cx="64"
                    cy="64"
                    r="56"
                    stroke={complianceScore >= 80 ? '#E8930A' : '#DC2626'}
                    strokeWidth="8"
                    fill="none"
                    strokeDasharray={`${2 * Math.PI * 56}`}
                    strokeDashoffset={`${2 * Math.PI * 56 * (1 - complianceScore / 100)}`}
                    strokeLinecap="round"
                  />
                </svg>
              </div>
            </div>
          </div>
          <div className="text-xs text-[#6B6B6B]">
            Generated by AI — GPT-4 Compliance Analyzer v2.1 — 2024-04-30 14:23 UTC
          </div>
        </div>

        <div className="space-y-3 mb-6">
          {categories.map(cat => (
            <div key={cat.id} className="border border-[#E0E0E0] rounded overflow-hidden">
              <button
                className="w-full bg-[#6B0D0D] text-white px-4 py-3 flex items-center justify-between hover:bg-[#5A0A0A]"
                onClick={() => toggleCategory(cat.id)}
              >
                <div className="flex items-center gap-3">
                  <span>{cat.title}</span>
                  <Badge variant={cat.status as any}>{cat.status}</Badge>
                </div>
                {expandedCategories[cat.id] ? <ChevronDown className="w-5 h-5" /> : <ChevronRight className="w-5 h-5" />}
              </button>
              {expandedCategories[cat.id] && (
                <div className="bg-white">
                  <table className="w-full text-sm">
                    <thead className="bg-gray-50">
                      <tr>
                        <th className="px-4 py-2 text-left">Requirement</th>
                        <th className="px-4 py-2 text-left">Assessment</th>
                        <th className="px-4 py-2 text-left">Regulatory Reference</th>
                        <th className="px-4 py-2 text-left">Protocol Section</th>
                      </tr>
                    </thead>
                    <tbody>
                      {cat.items.map((item, i) => (
                        <tr
                          key={i}
                          className={`border-t border-[#E0E0E0] ${
                            cat.status === 'pass' ? 'border-l-4 border-l-[#16A34A]' :
                            cat.status === 'warning' ? 'border-l-4 border-l-[#D97706]' :
                            'border-l-4 border-l-[#DC2626]'
                          }`}
                        >
                          <td className="px-4 py-3">{item.requirement}</td>
                          <td className="px-4 py-3">{item.assessment}</td>
                          <td className="px-4 py-3 text-[#6B6B6B]">{item.reference}</td>
                          <td className="px-4 py-3">
                            <a href="#" className="text-[#E8930A] hover:underline">{item.section}</a>
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              )}
            </div>
          ))}
        </div>

        <div className="bg-white border border-[#E0E0E0] rounded p-6 mb-6">
          <h3 className="text-lg text-[#6B0D0D] mb-4">Flagged Issues</h3>
          <table className="w-full text-sm">
            <thead className="bg-gray-50">
              <tr>
                <th className="px-4 py-2 text-left">Severity</th>
                <th className="px-4 py-2 text-left">Protocol Section</th>
                <th className="px-4 py-2 text-left">Issue Description</th>
                <th className="px-4 py-2 text-left">Regulatory Reference</th>
                <th className="px-4 py-2 text-left">Resolution Status</th>
              </tr>
            </thead>
            <tbody>
              {flaggedIssues.map((issue, i) => (
                <tr key={i} className="border-t border-[#E0E0E0]">
                  <td className="px-4 py-3">
                    <Badge variant={issue.severity as any}>{issue.severity}</Badge>
                  </td>
                  <td className="px-4 py-3">{issue.section}</td>
                  <td className="px-4 py-3">{issue.issue}</td>
                  <td className="px-4 py-3 text-[#6B6B6B]">{issue.reference}</td>
                  <td className="px-4 py-3">
                    <select className="px-2 py-1 border border-[#E0E0E0] rounded text-sm" defaultValue={issue.status}>
                      <option value="unresolved">Unresolved</option>
                      <option value="in_progress">In Progress</option>
                      <option value="resolved">Resolved</option>
                    </select>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        <div className="bg-white border border-[#E0E0E0] rounded p-6 mb-6">
          <h3 className="text-lg text-[#6B0D0D] mb-4">Compliance Score vs. Prior Reviews</h3>
          <div className="flex items-end gap-4 h-64">
            {historicalData.map((item, i) => (
              <div key={i} className="flex-1 flex flex-col items-center justify-end">
                <div
                  className={`w-full ${item.name === 'Current' ? 'bg-[#E8930A]' : 'bg-[#6B0D0D]'} rounded-t`}
                  style={{ height: `${item.score * 2}px` }}
                ></div>
                <div className="text-xs text-[#6B6B6B] mt-2">{item.name}</div>
                <div className="text-sm">{item.score}%</div>
              </div>
            ))}
          </div>
        </div>

        <Button variant="primary" className="flex items-center gap-2">
          <Download className="w-4 h-4" />
          Download PDF
        </Button>
      </div>
      {showProtocol && (
        <div className="w-80 bg-white border border-[#E0E0E0] rounded p-4">
          <div className="flex items-center justify-between mb-4">
            <h3 className="text-sm text-[#6B0D0D]">Protocol Preview</h3>
            <button onClick={() => setShowProtocol(false)} className="text-[#6B6B6B] hover:text-[#1A1A1A]">✕</button>
          </div>
          <div className="text-xs text-[#6B6B6B] space-y-2">
            <p><strong>Section 3.2:</strong> Informed Consent Process</p>
            <p><strong>Section 4.1:</strong> Inclusion Criteria</p>
            <p><strong>Section 6.3:</strong> Safety Monitoring</p>
          </div>
        </div>
      )}
    </div>
  );
}
